# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7affaf9aec1bf6582ff7c42f773c7a677bb309acdfc500c2fc11c66a8b486ab4905d1e51ff628534294b0fcf5121a69c785a8c9c47f07dc162142341814c794a

test:
  secret_key_base: eb64475c93a5ea9931a02c4e6fa2046c91ea32b4aa08439ae5775a97537159f0ba0f1a6daed92ab1a9cdcb43c4633e03c5f189b77877d83fce3b13ac36f17b52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
